#:schema node_modules/wrangler/config-schema.json
name = "workout-manager"
compatibility_date = "2024-11-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "workout-manager-db"
database_id = "890fa400-166e-4a48-9823-8ef0451222a8"
